site_name: Data Controller for SAS® Product Documentation
pages:
- Home: index.md
- Using Data Controller:
    - Overview: dc-overview.md
    - DC User Guide: dc-userguide.md
    - File Uploads: dcu-fileupload.md
- Configuring Data Controller:
    - Tables: dcc-tables.md
    - Security: dcc-security.md
    - Selectboxes: dcc-selectbox.md
    - Dates / Datetimes: dcc-dates.md
    - Emails: emails.md
    - Groups: groups.md
- Installing Data Controller:
    - System Requirements: dci-requirements.md
    - Backend: dci-backend.md
    - Frontend: dci-frontend.md
    - Troubleshooting: dci-troubleshooting.md
- Evaluation (Demo) Version:
    - Installation: dci-evaluation.md
    - Evaluation Licence: evaluation-licence-agreement.md
    - Other Licences: licences.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true

extra_css: ['font-awesome.css']

# Repository
repo_name: 'macropeople/dcdocs.github.io'
repo_url: 'https://github.com/macropeople/dcdocs.github.io'

theme:
  name: material
  logo: 'img/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  favicon: img/favicon.ico
  custom_dir: 'theme'
copyright: All rights reserved &copy;2020 Macro People Ltd.
