site_name: Data Controller for SAS® Documentation
site_url: https://docs.datacontroller.io
nav:
- Home: index.md
- User Guide:
    - Overview: dc-overview.md
    - DC User Guide: dc-userguide.md
    - Data Catalog: dcu-datacatalog.md
    - Data Lineage: dcu-lineage.md
    - File Uploads: dcu-fileupload.md
    - Filter Mechanism: filter.md
    - Table Viewer: dcu-tableviewer.md
- Configuration:
    - Dates / Datetimes: dcc-dates.md
    - Dynamic Cell Dropdown: dynamic-cell-dropdown.md
    - Emails: emails.md
    - Excel Formulas: excel.md
    - Groups: dcc-groups.md
    - Options: dcc-options.md
    - Row Level Security: row-level-security.md
    - Security: dcc-security.md
    - Selectboxes: dcc-selectbox.md
    - Tables: dcc-tables.md
    - Validations: dcc-validations.md
- Macros: macros.md
- Installation:
    - System Requirements: dci-requirements.md
    - SAS 9 Deploy: dci-deploysas9.md
    - SAS Viya Deploy: dci-deploysasviya.md
    - Troubleshooting: dci-troubleshooting.md
    - Dedicated STP: dci-stpinstance.md
- Evaluation (Demo) Version:
    - Installation: dci-evaluation.md
- Legal:
    - Privacy Policy: privacy.md
    - Evaluation Licence: evaluation-agreement.md
    - Other Licences: licences.md
- Videos: videos.md
- Roadmap: roadmap.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: true

plugins:
  - search:
      prebuild_index: true

extra:
  manifest: manifest.webmanifest

extra_css: ['font-awesome.css']

# Repository
repo_name: 'macropeople/dcdocs.github.io'
repo_url: 'https://github.com/macropeople/dcdocs.github.io'

theme:
  name: material
  logo: 'img/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  favicon: img/favicon.ico
  custom_dir: 'theme'
copyright: All rights reserved &copy;2021 Macro People Ltd.
