site_name: Data Controller for SAS® Product Documentation
pages:
- Home: index.md
- Using Data Controller:
    - DC Overview: dc-overview.md
    - DC User Guide: dc-userguide.md
- Configuring Data Controller:
    - Tables: dcc-tables.md
    - Security: dcc-security.md
    - Selectboxes: dcc-selectbox.md
- Installing Data Controller:
    - Backend: dci-backend.md
    - Frontend: dci-frontend.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true

extra_css: ['font-awesome.css']

# Repository
repo_name: 'macropeople/dcdocs.github.io'
repo_url: 'https://github.com/macropeople/dcdocs.github.io'

theme:
  name: material
  logo: 'img/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
copyright: All rights reserved &copy;2018 Macro People Ltd.
