site_name: Data Controller for SAS® Product Documentation
pages:
- Home: index.md
- Using Data Controller:
    - DC Overview: dc-overview.md
    - DC User Guide: dc-userguide.md
- Configuring Data Controller
    - Adding Users: dcc-users.md
    - Adding Tables

markdown_extensions:
 - admonition
 - pymdownx.superfences
 - codehilite
 - fontawesome_markdown
#extra_css: ['font-awesome.css']
theme: 
  name: material 
  logo: 'img/favicon.ico'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
copyright: All rights reserved &copy;2018 Macro People Ltd. 
